## 数组

In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [2]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

In [3]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

### 性能的差异
* NumPy是在一个连续的内存块中存储数据，独立于其他Python内置对象。NumPy的C语言编写的算法库可以操作内存，而不必进行类型检查或其它前期工作。比起Python的内置序列，NumPy数组使用的内存更少。

* NumPy可以在整个数组上执行复杂的计算，而不需要Python的for循环。

以下是一个例子：

In [4]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 28.8 ms, sys: 27.9 ms, total: 56.7 ms
Wall time: 55.4 ms


In [5]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 927 ms, sys: 375 ms, total: 1.3 s
Wall time: 1.33 s


In [6]:
type(my_arr)

numpy.ndarray

In [7]:
data = np.random.randn(2, 3); data

array([[-0.29138658,  0.22938563, -1.26022927],
       [ 0.47480551, -0.36230133, -0.27163937]])

In [8]:
data = data * 10; data

array([[ -2.91386578,   2.29385629, -12.60229273],
       [  4.74805508,  -3.62301334,  -2.71639367]])

In [9]:
data = data + data; data

array([[ -5.82773155,   4.58771258, -25.20458546],
       [  9.49611016,  -7.24602668,  -5.43278734]])

In [17]:
data.shape

(2, 3)

In [18]:
data.dtype

dtype('float64')

In [19]:
data1 = [1,2,3,4]
arr1 = np.array(data1); arr1

array([1, 2, 3, 4])

In [20]:
data2 = [1,2,3.4,5]
arr2 = np.array(data2); arr2

array([1. , 2. , 3.4, 5. ])

In [25]:
print(arr1.dtype, arr2.dtype)

int64 float64


In [26]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
np.empty((2,3,2))

array([[[2.47014246e-316, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [44]:
%time for i in range(100000000): pass

CPU times: user 4.03 s, sys: 1.74 ms, total: 4.03 s
Wall time: 4.5 s


In [45]:
%time for i in np.arange(100000000): pass

CPU times: user 7.44 s, sys: 772 ms, total: 8.22 s
Wall time: 8.52 s
